[pytest]
addopts = -ra -vv --strict-markers --cov=src --cov-report=term-missing --cov-report=html
testpaths = tests src/{{cookiecutter.package_name}}
python_files = test_*.py *_test.py
pythonpath = src
asyncio_mode = auto
markers =
    - unit: Schnelle, isolierte Unit-Tests ohne externe Ressourcen,
    - integration: Tests über mehrere Schichten (DB / Services / Dependencies),
    - e2e: End-to-End Tests über die laufende FastAPI-App,
    - slow: "Langsame Tests (z.B. mit echter DB)",

filterwarnings =
    ignore::DeprecationWarning:pkg_resources.*
